// <copyright file="ReactiveModelTests.cs" company="AillieoTech">
// Copyright (c) AillieoTech. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace AillieoUtils.Reactive.Tests
{
    using System;
    using NUnit.Framework;

    public sealed class ReactiveModelTests
    {
        [Test]
        public void GeneratedPropertyParticipatesInAutomaticDependencyTracking()
        {
            var model = new GeneratedPlayerModel();
            int runs = 0;
            int observed = 0;
            using (Rx.Observe(() =>
            {
                observed = model.Health;
                ++runs;
            }, (IReactiveScheduler)null))
            {
                Assert.AreEqual(100, observed);
                Assert.AreEqual(1, runs);

                model.Health = 80;
                Assert.AreEqual(80, observed);
                Assert.AreEqual(2, runs);

                model.Health = 80;
                Assert.AreEqual(2, runs, "Equality-filtered writes must not notify.");
            }
        }

        [Test]
        public void GeneratedPropertyAdapterSupportsTypedSubscriptions()
        {
            var model = new GeneratedPlayerModel();
            int calls = 0;
            int observed = 0;
            using (model.HealthProperty.Subscribe(value =>
            {
                observed = value;
                ++calls;
            }))
            {
                Assert.AreEqual(100, observed);
                Assert.AreEqual(1, calls);
                Assert.AreSame(model.HealthProperty, model.HealthProperty);

                model.Health = 75;
                Assert.AreEqual(75, observed);
                Assert.AreEqual(2, calls);
            }
        }

        [Test]
        public void GeneratedPropertyAdapterCanBeUsedAsAStaticDependency()
        {
            var model = new GeneratedPlayerModel();
            int runs = 0;
            using (Rx.Observe(() => ++runs, model.HealthProperty, null))
            {
                Assert.AreEqual(1, runs);
                model.Gold = 5;
                Assert.AreEqual(1, runs);
                model.Health = 90;
                Assert.AreEqual(2, runs);
            }
        }

        [Test]
        public void GeneratedPropertiesRespectBatchingAndChangeHooks()
        {
            var model = new GeneratedPlayerModel();
            int runs = 0;
            using (Rx.Observe(() =>
            {
                _ = model.Health;
                _ = model.Gold;
                ++runs;
            }, (IReactiveScheduler)null))
            {
                Rx.Batch(() =>
                {
                    model.Health = 70;
                    model.Health = 60;
                    model.Gold = 10;
                });

                Assert.AreEqual(2, runs);
                Assert.AreEqual(2, model.HealthChangeCount);
                Assert.AreEqual(70, model.LastOldHealth);
                Assert.AreEqual(60, model.LastNewHealth);
            }
        }

        [Test]
        public void ReactiveModelStateValidatesSlotsAndReturnsStableAdapters()
        {
            var state = new ReactiveModelState(1);
            int value = 42;
            Assert.AreSame(state.GetSource(0), state.GetSource(0));
            Assert.AreSame(state.GetProperty(0, () => value), state.GetProperty(0, () => value));
            Assert.Throws<ArgumentOutOfRangeException>(() => state.GetSource(1));
            Assert.Throws<ArgumentOutOfRangeException>(() => state.Notify(-1));
        }

        [Test]
        public void ClassAttributeGeneratesEligibleFieldsAndAllowsNameOverrides()
        {
            var model = new AutoGeneratedPlayerModel();
            int runs = 0;
            using (Rx.Observe(() =>
            {
                _ = model.Health;
                _ = model.DisplayName;
                ++runs;
            }, (IReactiveScheduler)null))
            {
                Assert.AreEqual(100, model.Health);
                Assert.AreEqual("Player", model.DisplayName);
                Assert.AreEqual(1, runs);

                model.Health = 75;
                model.DisplayName = "Aillieo";

                Assert.AreEqual(3, runs);
            }
        }

        [Test]
        public void ClassAttributeExcludesNonReactiveAndUnsupportedFields()
        {
            var model = new AutoGeneratedPlayerModel();

            model.SetCachedScore(42);

            Assert.AreEqual(42, model.ReadCachedScore());
            Assert.AreEqual(7, model.SeedValue);
            Assert.AreEqual(4, AutoGeneratedPlayerModel.Metadata);
            var flags = System.Reflection.BindingFlags.Instance |
                System.Reflection.BindingFlags.Static |
                System.Reflection.BindingFlags.Public |
                System.Reflection.BindingFlags.NonPublic;
            Assert.IsNull(typeof(AutoGeneratedPlayerModel).GetProperty("CachedScore", flags));
            Assert.IsNull(typeof(AutoGeneratedPlayerModel).GetProperty("Seed", flags));
            Assert.IsNull(typeof(AutoGeneratedPlayerModel).GetProperty("MaximumPlayers", flags));
            Assert.IsNull(typeof(AutoGeneratedPlayerModel).GetProperty("InstanceCount", flags));
        }
    }

    internal sealed partial class GeneratedPlayerModel
    {
        [Reactive]
        private int health = 100;

        [Reactive]
        private int gold;

        internal int HealthChangeCount { get; private set; }

        internal int LastOldHealth { get; private set; }

        internal int LastNewHealth { get; private set; }

        partial void OnHealthChanged(int oldValue, int newValue)
        {
            ++this.HealthChangeCount;
            this.LastOldHealth = oldValue;
            this.LastNewHealth = newValue;
        }
    }

    [ReactiveModel]
    internal sealed partial class AutoGeneratedPlayerModel
    {
        private const int MaximumPlayers = 4;
        private static int instanceCount;
        private readonly int seed = 7;
        private int health = 100;

        [Reactive("DisplayName")]
        private string playerName = "Player";

        [NonReactive]
        private int cachedScore;

        internal static int Metadata => MaximumPlayers + instanceCount;

        internal int SeedValue => this.seed;

        internal void SetCachedScore(int value)
        {
            this.cachedScore = value;
        }

        internal int ReadCachedScore()
        {
            return this.cachedScore;
        }
    }
}
